/*
 * File: app/store/SymbolsStore.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HeaderLeftRight.store.SymbolsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'HeaderLeftRight.model.SymbolModel',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'SymbolsStore',
            model: 'HeaderLeftRight.model.SymbolModel',
            proxy: {
                type: 'jsonp',
                extraParams: {
                    access_key: 'fb6e8c73be27e96f7392a4db33fa5fc5'
                },
                url: 'https://api.exchangeratesapi.io/v1/symbols',
                reader: {
                    type: 'json',
                    transform: function(data) {
                        var symbols = data.symbols;

                        data = Object.keys(symbols).map((symbol) => {
                            return {
                                symbol: symbol,
                                value: symbols[symbol]
                            };
                        });

                        return data;
                    }
                }
            }
        }, cfg)]);
    }
});