/*
 * File: app/view/MyPanelViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HeaderLeftRight.view.MyPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mypanel',

    onRateGridAfterRender: function(component, eOpts) {
        var rateGrid = Ext.ComponentQuery.query('#rateGrid')[0];
        var store = rateGrid.getStore();

        store.load({
            scope:this,
            callback: function(records, operation, success) {
                store.setData(records);
            }
        });

        var symbolGrid = Ext.ComponentQuery.query('#symbolGrid')[0];
        var symbolStore = symbolGrid.getStore();

        symbolStore.load({
            scope:this,
            callback: function(records, operation, success) {
                symbolStore.setData(records);
            }
        });

    }

});
