/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.9.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.3.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.3.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HeaderLeftRight.view.MyPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel',

    requires: [
        'HeaderLeftRight.view.MyPanelViewModel',
        'HeaderLeftRight.view.MyPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.filters.filter.List',
        'Ext.grid.column.Number',
        'Ext.grid.filters.Filters',
        'Ext.toolbar.Fill',
        'Ext.form.Label'
    ],

    controller: 'mypanel',
    viewModel: {
        type: 'mypanel'
    },
    border: false,
    height: 600,
    style: {
        margin: 'auto'
    },
    width: '800px',
    bodyBorder: false,
    title: '',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            height: 66,
            style: {
                'background-color': '#e4e4e4'
            },
            items: [
                {
                    xtype: 'button',
                    height: 40,
                    id: 'menuBtn',
                    minWidth: 40,
                    iconCls: 'fas fa-bars',
                    text: '',
                    listeners: {
                        click: 'onMenuBtnClick'
                    }
                },
                {
                    xtype: 'textfield',
                    height: 54,
                    id: 'currentSymbolText',
                    style: {
                        'font-size': '18px !important'
                    },
                    width: 685,
                    fieldLabel: '',
                    value: 'text',
                    readOnly: true,
                    editable: false
                },
                {
                    xtype: 'button',
                    height: 40,
                    id: 'refreshBtn',
                    minWidth: 40,
                    iconCls: 'fas fa-redo-alt',
                    text: '',
                    listeners: {
                        click: 'onRefreshBtnClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'panel',
            defaultAlign: 'w-w',
            flex: 2,
            title: '',
            dockedItems: [
                {
                    xtype: 'gridpanel',
                    dock: 'left',
                    id: 'symbolGrid',
                    resizable: false,
                    scrollable: 'vertical',
                    width: 234,
                    title: '',
                    store: 'SymbolsStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: '100%',
                            dataIndex: 'value',
                            text: ''
                        }
                    ],
                    listeners: {
                        rowclick: 'onSymbolGridRowClick'
                    }
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    height: 450,
                    id: 'rateGrid',
                    resizable: false,
                    resizeHandles: 'e',
                    scrollable: 'vertical',
                    title: '',
                    enableColumnResize: false,
                    store: 'RatesStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: '50%',
                            dataIndex: 'symbol',
                            text: 'Symbol',
                            filter: {
                                type: 'list'
                            }
                        },
                        {
                            xtype: 'numbercolumn',
                            width: '50%',
                            align: 'end',
                            dataIndex: 'rate',
                            text: 'Currecy Value'
                        }
                    ],
                    listeners: {
                        afterrender: 'onRateGridAfterRender',
                        rowclick: 'onRateGridRowClick'
                    },
                    plugins: [
                        {
                            ptype: 'gridfilters'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: 86,
            items: [
                {
                    xtype: 'toolbar',
                    border: '1px solid #000000',
                    height: 86,
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'label',
                            id: 'resultLbl',
                            style: {
                                'font-size': '40px',
                                'font-weight': 'bold'
                            },
                            text: '1 USD = ?'
                        },
                        {
                            xtype: 'tbfill'
                        }
                    ]
                }
            ]
        }
    ]

});